### ISSUE TITLE
p639拉克万纳证券公司估值问题

### ISSUE THREAD

**Issue by boduane** [SecurityAnalysisLearningGroup/issue-tracker#22]
若以10%为标准估计这些利息收入，那么格兰奥尔登公司的债券只值37美分，是怎么算出来的?

**Comment by tcfh2016** [comment]
多谢 @Haidl 的提醒，我如上的理解确实有问题： 如上叙述的过程可以解释括号附注里“公司面值为60美元，实际售价为37美元”的说法，但以此论证“格兰奥尔登公司的债券一美元只值37美分”的做法是错误的。

按照Just的提示，当时拉克万纳证券公司的股价为23美元，而实际上它的资产包括每股1美元的现金，以及对应每股60美元面值的格兰奥尔登的债券：

- 如果按照股价去推算资产，相当于 23美元/股 = 1美元现金/股 + 22美元债券/股。
- 而实际上债券的价值为 60美元/股。
- 所以，相当于60美元/股的债券在股价里面仅仅体现出了22美元/股的价值，即1美元只值 22/60 = 0.36666美元，相当于37美分。
