### ISSUE TITLE
格雷厄姆成长股估值公式

### ISSUE THREAD

**Issue by boduane** [SecurityAnalysisLearningGroup/issue-tracker#23]
在估值公式的选择上，笔者最喜欢也最常用的公式，是价值投资的鼻祖-格雷厄姆的公式。

格雷厄姆在《聪明的投资者》中曾经提供过“一个简单的公式用于成长股的评价”。这个公式得到的价值数据相当接近于那些用更精密的数学方法计算出的结果。公式是：
>价值＝当前（普通）收益×（8.5+预期年增长率×2）

这个增长数应该是对下一个7至10年的预测。

- 小小辛巴注：在运用这个公式时预期年增长率应去除百分比，比如说，预期的年增长率为10%时，则代入公式的数字应为10，而不是10%。如果用静态市盈率衡量，则桂林三金的价值＝2010年每股收益0.4385元（十股转增三股摊薄）×（8.5+预期年增长率15.02×2）＝16.89979元≈16.90元

**Comment by boduane** [comment]
仙人掌:
这个公式估值，实际上就是每股收益乘市盈率，市盈率=8.5+每年预期收益率＊2，格老认为一般公司市盈率12—12.5。
这个经验公式，需要炒股验证后才能作为支点。
实际上，格老更看重的是每股收益，用10年的数据来分析，这更靠谱。
事实上，公司未来的发展受管制、政策、环境、竞争等诸多因素的影响，经验公式仅作参考。

**Comment by tcfh2016** [comment]
Terry的疑问：

>@波段 这个估值公式是从哪里得来的？公式中，有3个参数存在疑问。分别是：8.5、预期增长率、2

东华的回复：

>价值秤: 格雷厄姆估值计算公式（二） 深度好文|全文3357字 阅读需要4分钟 本来源：文关键词（格雷厄姆、价值投资、估值公式、安全边际、计算价值） 格雷厄姆的成长... - 雪球  https://xueqiu.com/7397106194/92351828

![180325](https://user-images.githubusercontent.com/17757622/37881582-7f25eaee-30d5-11e8-9ccf-919dc1954231.jpg)

结论：

- 东华猜测8.5是个经验值，预期增长率是近几年的平均增长率，2倍不知原因。整个公式看起来是经验公式。
    - 东华的补充：格老给这个公式的唯一定语是“十分简便”，没说它可靠。在《聪明的投资者》455页，专门讲了，这个公式并没有给出成长股的“实际价值”，只是大致给出了当时流行的复杂计算方法所得出的结果。以格老一贯的立场，从不认为存在精确的计算公式价值的方法。只有粗略的估计一个价值的区间。
    - 仙人掌的补充：这个经验公式，猜测是大量数据统计后，推导出来的！当成千上万的数据进行统计分析生成图形后，就容易发现其变化的规律，数据样本采集量越大，精确度就越高。强调”预期”增长率，而预期是静态估算的增长率，实际发生的增长率才是动态的增长率。

- Terry觉得这篇文章没有回答他的问题，觉得该模型不可靠，连基本的逻辑关系没有表达清楚。

**Comment by Terryho2005** [comment]
@boduane 书中的意思是，用来计算预期收益率，并非用来计算价值的。

**Comment by Terryho2005** [comment]
预期增长率是依据什么来确定？

**Comment by boduane** [comment]
预期增长率应该是近几年的平均增长率

**Comment by Terryho2005** [comment]
书中是否给出预期增长率的定义？ @boduane
