### ISSUE TITLE
请问大家是怎样判断美国水务和电力公司的资本结构是高负债型？

### ISSUE THREAD

**Issue by Terryho2005** [SecurityAnalysisLearningGroup/issue-tracker#28]
在书中第624页表40-3，请问大家是怎样判断美国水务和电力公司的资本结构是高负债型？

**Comment by tcfh2016** [comment]
个人理解是依据1921年的`归属于普通股股东的净利润`与`固定费用与优先股股息`来确认的：

固定费用与优先股股息|归属于普通股股东的净利润|
----|----|
 6 353 000 | 339 000|

优先股股息与股东的净利润相差18倍之多，所以公司发行的优先证券的比例应该大大超过普通股。在P619列举的三家公司，格雷厄姆认为公司C已经属于高负债型企业，其优先证券与普通股的比例为2:1。

**Comment by Terryho2005** [comment]
$6,353,000是包含固定费用（fixed charge，也可译作固定支出），这个数字并不是完全反映优先股股息。
