### ISSUE TITLE
《证券分析》下册第13天思考题：计算宁德时代2016年的每股账面价值。

### ISSUE THREAD

**Issue by boduane** [SecurityAnalysisLearningGroup/issue-tracker#29]
本章的思考题：
根据宁德新时代的招股书，计算公司2016年的每股账面价值。

1，**用全部有形资产之和减去所有负债及非公众股权益，然后除以股票数量，就得到了每股的账面价值**。

有形资产之和：使用招股说明书之资产负债表之固定资产与在建工程之和.
2016年数据：

- 有形资产之和：固定资产和在建工程3,727,473,865.79+1,226,129,855.44=4,953,603,721.23
- 减去所有负债：采用负债合计        12,797,195,300.25
- 减去非公众股权益 取报表少数股东权益     302,472,760.51
- 账面价值=-8,146,064,339.53
- 每股账面价值=-4.17元

那么这是对的还是错的？哪个数字取错了呢？这个应该是错的。

再来一遍，百度有形资产 ：
>有形资产（Tangible asset/Physical assets）是指那些具有实物形态的资产，包括固定资产和流动资产。如存货、对外投资、货币资产、应收账款等。有形资产有狭义的概念和广义的概念之分。总的来说，有形资产就是有一定实物形态的资产。以具体物质产品形态存在的资产，包括生产有形资产和非生产有形资产。

照搬如下
- 有形资产：固定资产3,727,473,865.79
- +流动资产合计21,761,324,772.53
- +长期股权投资310,725,425.65
- +可供出售金融资产1,547,503,500.00
- =27,347,027,563.97
- 减去所有负债：采用负债合计        12,797,195,300.25
- 减去非公众股权益 取报表少数股东权益     302,472,760.51
- 账面价值=14,247,359,503.21
- 股本数更正为=613,321,800.00
- 每股账面价值=23.23元

对吗？请指正。

2，根据653定义，将有形资产理解为资产减去无形资产

- 资产负债表资产总计:40,883,616,374.70
- 减去无形资产：1,162,449,058.99
- 减去商誉：100,419,270.78
- （减去商标：
- 减去专利权：
- 减去特许经营权：
- 减去租赁权：以上几项包含在无形资产中？！）
- 有形资产价值等于39,620,748,044.93
- 每股账面价值等于39,620,748,044.93/1,955,193,267.00=20.26元

对吗，请指正。

3，对照招股说明书采用的每股净资产：

- （归属于发行人股东的净资产=期末归属于母公司股东权益）/期末股本总额=8.42元
- 归属于母公司股东权益合计15,488,646,283.32
- 2016股本数=613,321,800.00（之前股本数用的都是1,955,193,267.0）
- 每股权益=25.25

不等于使用17股本1,955,193,267.0来除=7.92元，和8.42接近。8.42怎么算的？

**Comment by boduane** [comment]
4，使用P654上面的公式：普通股股本加盈余项目减无形资产除以普通股数量=每股普通股账面价值
2016普通股股本613,321,800.00
+盈余项目：
盈余公积           299,841,288.90
资本公积           11,438,488,516.76
存货跌价准备    153,641.09万元即1，536，410，900
-无形资产：
无形资产：621,645,950.26（包含土地使用权263,243,500 元）
商誉：      100,419,270.78
=13,165,997,284.62
/2016普通股股本613,321,800.00
=21.47元

与8.42的净资产相差依然很大。
/2017股本1,955,193,267.00
=6.73元
（13、计算2015年、 2016年每股指标时，为便于比较，根据公司2017年资本公积转增股本情况
进行了调整。）是股本算错了吗？

招股书p37（11、无形资产占净资产比例＝（无形资产+开发支出+商誉－土地使用权）／期末净资产；）
可见，无形资产=无形资产+开发支出+商誉－土地使用权《------------气死人的等式。
土地使用权（招股书P293）          263,243,500 元
那么是无形资产算错了吗？

**Comment by Terryho2005** [comment]
这是我计算宁德时代2016年每股收益的方法，请参考，欢迎提议。

![image](https://user-images.githubusercontent.com/7948160/38070276-c272ab32-334d-11e8-82f2-b971fde1f76f.png)

**Comment by tcfh2016** [comment]
@Terryho2005 在如上你列示的表格中，“资产总计”、“无形资产”、“商誉”以及“负债合计”均是2016年度数据，但为何总股本采用了2017年度的1,955,193,267.00，而不是2016年度的613,321,800.00 ？

我采用同样的方式计算，即`有形资产 - 减去全部债务以及优先级别高于普通股的股票，然后除以总数`的方式：

    资产总计 - 无形资产 - 商誉 - 负债合计 - 少数股东权益
    = 28,588,314,344.08 - 621,645,950.26 
       - 100,419,270.78 - 12,797,195,300.25 
       - 302,472,760.51
    = 23 192 260 050.99 元

因此得每股账面价值 = 23 192 260 050.99 元 / 1,955,193,267.00 = 11.86元。与你不同的是我在其中多减掉了`少数股东权益`，我认为其不属于普通股东的权益，你认为有没有问题？

**Comment by tcfh2016** [comment]
@boduane 对于你前面提到的4点，有下面几个观点：

- 对于第1点，更正之后的算法正确，但是其中的股本使用了2017年度的，因此计算的2016年度每股账面价值不对。
- 对于第2点，你计算除了有形资产价值，但在计算账面价值时漏减了“债务”一项。
- 对于第3点，可否告知8.42的数据从招股说明书的哪页找来的？
- 对于第4点，你使用的`存货跌价准备`从哪里来的？似乎不对，因为2016年度存货为1,359,772,316.12，而你的跌价准备为1，536，410，900，已经超过存货了。

**Comment by boduane** [comment]
修订4：
p654公式      每股普通股的账面价值=（普通股股本+盈余项目-无形资产）/普通股数量

2016年数据：
普通股股本：613,321,800.00
盈余项目：
        盈余公积：299,841,288.90元
        股本溢价：11，350，298，400元（1,135,029.84万元）
        储备金：1，536，410，900元（存货跌价准备，其他储备为找到，稍后继续找）
 无形资产：
        无形资产：621,645,950.26元（包含土地使用权263,243,500 元）
        商誉：      100,419,270.78元
so：
（613,321,800.+299,841,288.90+11，350，298，400+1，536，410，900--621,645,950.26--100,419,270.78）/613,321,800=21.32元

储备金一块稍后继续明确。

**Comment by boduane** [comment]
@tcfh2016 
第1、2点，你说得对，谢谢。
第3点，招股书P38，第五行
归属于发行人股东的每股净资产（元/股） | 12.63 | 8.42 | 0.89


4存货跌价准备见p367，第5行应为176，638，600元，前面错取了原值数据。

**Comment by tcfh2016** [comment]
@boduane 确实宁德时代2016年的每股净资产为8.42元与我们计算出来的每股账面价值20+元（按照MBALIB里面[每股净资产](http://wiki.mbalib.com/wiki/%E8%82%A1%E7%A5%A8%E7%9A%84%E5%87%80%E5%80%BC)的定义，每股净资产就是每股账面价值）相差比较大。这里有好几种每股账面价值的计算方法：

**方法一**
MIBLIB里面的定义每股账面价值为（总资产 - 总负债）/ 股数：

    (28,588,314,344.08 - 12,797,195,300.25) / 613,321,800.00
    = 25.74元。

**方法二**
按照《证券分析》上面计算每股账面价值的方法，也即是你的那种计算方法计算每股账面价值为：

    （普通股 + 盈余项目 - 无形资产） / 已发行的股票数
    = (股本 + 资本公积 + 盈余公积 + 未分配利润 - 无形资产 - 商誉) / 股本
    = （613,321,800.00 + 11,438,488,516.76 + 299,841,288.90 + 3,135,427,787.32 - 621,645,950.26 - 100,419,270.78）/ 613,321,800.00
    = 24.07元。

**方法三**
按照《证券分析》上面有形资产 - 减去全部债务以及优先级别高于普通股的股票，然后除以总数的方式：

    资产总计 - 无形资产 - 商誉 - 负债合计 - 少数股东权益
    = (28,588,314,344.08 - 621,645,950.26  - 100,419,270.78 - 12,797,195,300.25 - 302,472,760.51)/613,321,800.00
    = 14 766 581 062.28 /613,321,800.00
    = 24.07元。

所以对于上面每股8.42的净资产确实不知道是怎么得来的。如果按照8.42去反推，那么净资产为：
    8.42 * 613,321,800.00 = 5 164 169 556.0 元。

**Comment by tcfh2016** [comment]
对于2017年的每股账面价值计算如下。

**从权益角度计算**

    （普通股 + 盈余项目 - 无形资产） / 已发行的股票数
    = (股本 + 资本公积 + 盈余公积 + 未分配利润 + 其他综合收益 - 无形资产 - 商誉) / 股本
    = (1,955,193,267.00 + 15,090,559,281.03 + 647,649,983.25 + 6,759,537,028.25 +248,500,011.58 - 1,408,760,249.33 - 100,419,270.78) / 1,955,193,267.00
    =11.861875980467971
    = 11.86元

**从资产角度计算**

    资产总计 -  负债合计 - 无形资产 - 商誉 - 少数股东权益
    = (49,662,885,758.45 - 23,191,646,660.83 - 1,408,760,249.33 - 100,419,270.78 - 1,769,799,526.51) / 1,955,193,267.00
    = 11.86187598046797 元
    = 11.86元

**Comment by boduane** [comment]
未分配利润和盈余公积同属于盈余项目，应加入分子之“盈余项目”，稍后更改。

**Comment by boduane** [comment]
再修订方法4：
修订====未分配利润和盈余公积同属于盈余项目，应加入分子之“盈余项目”

p654公式 每股普通股的账面价值=（普通股股本+盈余项目-无形资产）/普通股数量

2016年数据：
普通股股本：613,321,800.00
盈余项目：
盈余公积：299,841,288.90元
未分配利润：3,135,427,787.32
股本溢价：11，350，298，400元（1,135,029.84万元）
储备金：176，638，600元（存货跌价准备，其他储备暂未找到，稍后继续找）
无形资产：
无形资产：621,645,950.26元（包含土地使用权263,243,500 元）
商誉： 100,419,270.78元
so：
（613,321,800.+299,841,288.90+11，350，298，400+176，638，600--621,645,950.26--100,419,270.78）/613,321,800=14853462655.18/613,321,800=24.21元

宁德时代2016年每股普通股的账面价值=18.62元

储备金一块稍后继续明确。 @Terryho2005 @tcfh2016 @Haidl @A417273134

**Comment by boduane** [comment]
同样的方法计算2017年宁德时代账面价值

宁德时代2017年普通股账面价值：
2017数据
普通股股本：1,955,193,267.00
盈余项目：
盈余公积：647,649,983.25元
股本溢价：15,037,326,300元（1,135,029.84万元）
储备金：227,885,400元（存货跌价准备，其他储备暂未找到，稍后继续找）
无形资产：
无形资产：1,408,760,249.33元（包含土地使用权263,243,500 元）
商誉： 100,419,270.78元

计算：（1,955,193,267.00+647,649,983.25+15,037,326,300+227,885,400--1,408,760,249.33--100,419,270.78）/1,955,193,267=16358875430.14/1,955,193,267=8.37元

宁德时代2017年普通股每股账面价值     8.37元        （比2016年下降55%，股本数增长219%）
宁德时代2017年普通股账面价值            164亿元

**Comment by boduane** [comment]
貌似可以关闭了。

**Comment by Terryho2005** [comment]
宁德时代2016年的账面价值是147.6亿。如果账面价值少1倍，股本增加2倍以上，而每股收益只是缩小1倍，这是不合理的。

**Comment by boduane** [comment]
加到最后，发现又成为了tcfh2016 的方法二。

**Comment by boduane** [comment]
这个数字是合理的。我简单算了下:账面价值10000，股数200，每股账面价值50。增50%，218%到15000，636。相除得23.6元，大致为50的一半。我第一感觉也是数字不对，其实正常。或者这样算:10000/50=200，15000/25=600。600/200=3。分子增一半，分母减一半，除数大3倍。
